### ISSUE TITLE
Feature request: do this for all links please

### ISSUE THREAD

**Issue by kazink** [nralbrecht/pinned-tab-fix#11]
It's nice the links from pinned tabs open on the far right, but I would like the links from **all** tabs open on far right. I could not find any add-on, that does it and is compatible with Firefox 57. Could you make it (as an option perhaps), please?

**Comment by nralbrecht** [comment]
Hi, I like your idea an I am shure you are not the only person with this problem. I could not find a dedicated add-on either. There are two options I could do:

1. Add an option as you said
2. Create a dedicated add-on

I would prefer 2. because this ist not really the problem this add-on is trying to solve. It would be also be better searchable under its own name. Please let me know what you think about my Idea.

**Comment by kazink** [comment]
Thanks. While it seems more plausible for me to have one multi-purpose add-on (less hassle if someone changes his mind - he will just switch an option instead of searching for a new add-on) you have the point about better searchability.
Do as you feel is better. For me it's not that important if it will be another add-on.

**Comment by nralbrecht** [comment]
Allright I have created a new addon. You can find it [here](https://addons.mozilla.org/de/firefox/addon/everything-right/).

If you find any issues, please let me know [here](https://github.com/nralbrecht/everything-right/issues).

**Comment by kazink** [comment]
Thanks

**Comment by Forkest** [comment]
It could have been solved by flipping a built-in setting `browser.tabs.insertRelatedAfterCurrent` in `about:config`.
